apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fmcd-inference-config
data:
  models.yaml: |
{{ required "Передайте --set-file serviceConfig=configs/models.yaml" .Values.serviceConfig | indent 4 }}
