apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fmcd-inference-config
data:
  models.yaml: |
    models:
      {{- range .Values.models }}
      - name: "{{ .name }}"
        artifacts_dir: "{{ .artifactsDir }}"
        weights_file: "{{ .weightsFile }}"
        schema_file: "{{ .schemaFile }}"
        calibrators_file: "{{ .calibratorsFile }}"
        freq_encoding_file: "{{ .freqEncodingFile }}"
      {{- end }}
    inference:
      device: "{{ .Values.inference.device }}"
      infer_batch_size: {{ .Values.inference.inferBatchSize }}
      chunk_size: {{ .Values.inference.chunkSize }}
    s3:
      endpoint_url_env: "S3_ENDPOINT_URL"
      access_key_env: "S3_ACCESS_KEY"
      secret_key_env: "S3_SECRET_KEY"
      bucket_in_env: "S3_BUCKET_IN"
      bucket_out_env: "S3_BUCKET_OUT"
      region_env: "S3_REGION"
      use_ssl_env: "S3_USE_SSL"
      verify_ssl_env: "S3_VERIFY_SSL"
    task:
      progress_update_interval_sec: {{ .Values.task.progressUpdateIntervalSec }}
