apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fmcd-inference
spec:
  selector:
    app: fmcd-inference
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
